### PR TITLE
Views improvements for transations

### PR DESCRIPTION
**Pull request by VerioPL**
As in title, first part

### CODE REVIEW

**Comment by VerioPL** [comment]
Also BON to BONUS update

**Comment by VerioPL** [comment]
And missing block "Click [BBCODE] to enable editor"

**Comment by VerioPL** [comment]
Revert of BON->BONUS update, need to be fixed

**Comment by HDVinnie** [comment]
Few issues spotted. No need to call the facade.  

{{ Illuminate\Support\Str::lower(trans('common.comment')) }}

All need is {{ str_lower(trans('common.comment')) }}

Same with your str_upper which is spelt wrong

**Comment by VerioPL** [comment]
Okay, don't merge that, I will fix all of that later

**Comment by VerioPL** [comment]
Please don't merge
Call to undefined function str_upper()

Any ideas?

**Comment by VerioPL** [comment]
Now it's working! 🥇

**Pull request merged**
