### PR TITLE
Change sorting for topics

### PR DESCRIPTION
**Pull request by Hyleus**
This has the effect that topics with new replies get bumped to the top.

### CODE REVIEW

**Comment by HDVinnie** [comment]
This is no good because the updated_at column changes when the topic is viewed and view count gets updated. So it won't work for topics with new comments as your thinking.

**Comment by Hyleus** [comment]
Fixed

**Comment by HDVinnie** [comment]
shouldn't you also be setting the new last_reply_at in the newTopic function?

**Comment by Hyleus** [comment]
OK, updated it again.

**Pull request merged**
